package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.event.ActionEvent;

import javafx.scene.control.RadioButton;

import javafx.scene.control.DatePicker;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class Main_Menu_EmployeeController {
	@FXML
	private Button txtAdd;
	@FXML
	private TextField txtFirst_Name;
	@FXML
	private TextField txtLast_Name;
	@FXML
	private TextField txtEmail;
	@FXML
	private TextField txtPhone;
	@FXML
	private TextField txtAddress;
	@FXML
	private DatePicker dtDOB;
	@FXML
	private TextField txtID;
	@FXML
	private RadioButton rdActive;
	@FXML
	private TableView TableEmployees;
	@FXML
	private TableColumn EmployeesFirst_Name;
	@FXML
	private TableColumn EmployeesLast_Name;
	@FXML
	private TableColumn EmployeesID;
	@FXML
	private TableColumn EmployeesEmail;

	// Event Listener on Button.onAction
	@FXML
	public void setAdminSaveButtonClick(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void setAdminClearButtonClick(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void setAdminViewButtonClick(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void setAdminRefreshButtonClick(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void setAdminSearchButtonClick(ActionEvent event) {
		// TODO Autogenerated
	}
}
